from os import environ

MAIL_USERNAME=environ.get('MAIL_USERNAME')
MAIL_PASSWORD=environ.get('MAIL_PASSWORD')
MAIL_PORT=environ.get('MAIL_PORT')
MAIL_DEFAULT_SENDER=environ.get('MAIL_DEFAULT_SENDER')
MAIL_TO=environ.get('MAIL_TO')
MAIL_SERVER=environ.get('MAIL_SERVER')
RECAPTCHA_SITE_KEY=environ.get('RECAPTCHA_SITE_KEY')
RECAPTCHA_SECRET_KEY=environ.get('RECAPTCHA_SECRET_KEY')